version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      PGDATA: "D:/test"
    ports:
    - "5432:5432"
    volumes:
    - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:5433